version: '3.8'
services:
  dynamodb-local:
    #TODO pin these versions?
    image: "amazon/dynamodb-local:latest"
    container_name: dacatours-dynamodb-local
    ports:
      - "8005:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

  dynamodb-admin:
    #TODO pin these versions?
    image: aaronshaf/dynamodb-admin:latest
    container_name: dacatours-dynamodb-admin
    ports:
      - "8004:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dacatours-dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: unless-stopped
